### ISSUE TITLE
How install/add it to godot?

### ISSUE THREAD

**Issue by jeremi360** [GodotExplorer/editor-server#1]
I don't know what to do with it.
Why there is no README.md fro noobs like me ;) ?
Should I : 
* put it may every godot project folder
* put it some where in godot src and complie with it
* or do something else?

**Comment by Geequlim** [comment]
The documentation will be written by others as my English is so poor to do that.

The modules should be compile with godot editor to work.

BTW What you want from these modules.

**Comment by jeremi360** [comment]
I just want to use your godot-tools vscode extesion.

> The modules should be compile with godot editor to work.

But i don't know where put it in godot source to compile it right

**Comment by Geequlim** [comment]
You can put the folder `editor_server` and `vscode_tools` into the `modules` folder in godot source code folder and compile the godot editor.

If you don't need autocompletion for native classes defined in your private modules. You don't need to do that.

**Comment by jeremi360** [comment]
This means I don't need that :) , But Thanks any way.
